CREATE TABLE ALUMNOS (
  ID_ALUMNO NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL,
  PROMEDIO FLOAT
);

SELECT * FROM ALUMNOS4;

INSERT INTO ALUMNOS (ID_ALUMNO, NOMBRE, PROMEDIO)
VALUES (1, 'CARLOS', 10);
INSERT INTO ALUMNOS (ID_ALUMNO, NOMBRE, PROMEDIO)
VALUES (2, 'ANTONIO', 7);
INSERT INTO ALUMNOS (ID_ALUMNO, NOMBRE, PROMEDIO)
VALUES (3, 'CARLOS', 5);
INSERT INTO ALUMNOS (ID_ALUMNO, NOMBRE, PROMEDIO)
VALUES (4, 'ANA', 10);
INSERT INTO ALUMNOS (ID_ALUMNO, NOMBRE, PROMEDIO)
VALUES (5, 'LEONOR', 0);

UPDATE ALUMNOS SET PROMEDIO=0 WHERE PROMEDIO<7;
DELETE FROM ALUMNOS WHERE NOMBRE LIKE 'A%';


SELECT * FROM ALUMNOS;

DROP TABLE ALUMNOS4;

ALTER TABLE ALUMNOS  ADD (APELLIDO_PATERNO VARCHAR2 (30));
ALTER TABLE ALUMNOS  ADD (APELLIDO_MATERNO VARCHAR2 (20));
ALTER TABLE ALUMNOS  ADD (SEMESTRE NUMBER DEFAULT(4));

UPDATE ALUMNOS SET APELLIDO_PATERNO = 'LOPEZ' WHERE ID_ALUMNO =5;
UPDATE ALUMNOS SET APELLIDO_PATERNO = 'ORTIZ' WHERE ID_ALUMNO =3;
UPDATE ALUMNOS SET APELLIDO_PATERNO = 'HERNANDEZ' WHERE ID_ALUMNO =1;
UPDATE ALUMNOS SET APELLIDO_MATERNO = 'LOPEZ' WHERE ID_ALUMNO =5;
UPDATE ALUMNOS SET APELLIDO_MATERNO = 'HERRERA' WHERE ID_ALUMNO =3;
UPDATE ALUMNOS SET APELLIDO_MATERNO = 'CRUZ' WHERE ID_ALUMNO =1;

--- BORRAR REGISTROS DONDE EL PROMEDIO SEA CERO Y SEMESTRE SEA CINCO. 

DELETE FROM ALUMNOS WHERE PROMEDIO=10 AND SEMESTRE=5;

-- BORRAR TODO LOS REGRISTROS DOND EL NOBRE SEA ANA Y EL SEMESTRE SEA 4

DELETE FROM ALUMNOS WHERE NOMBRE='ANA' AND SEMESTRE=4;