CREATE TABLE PRODUCTO2(
PK_PRODUCTO INTEGER PRIMARY KEY,
ID_UNO NUMBER,
NOMBRE VARCHAR2(50) NOT NULL,
CATEGORIA VARCHAR2 (20),
PRECIO_UNITARIO NUMBER(8, 2),
CADUCIDAD DATE,
EXISTENCIA NUMBER (8, 2)
);



SELECT * FROM PRODUCTO2;

INSERT INTO PRODUCTO2 (
    PK_PRODUCTO, ID_UNO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, CADUCIDAD, EXISTENCIA) 
    VALUES (4, 1, 'CEREALES', 'PRIMARIA', 2500, TO_DATE('25/06/2003','DD/MM/YYYY'), 1
);

ALTER TABLE PRODUCTO2 DROP COLUMN MARCA;
ALTER TABLE PRODUCTO2 DROP COLUMN STOCK_MINIMO;

SELECT * FROM PRODUCTO2;

ALTER TABLE PRODUCTO2 add
(STOCK_MINIMO NUMBER(38));

ALTER TABLE PRODUCTO2 add
(MARCA VARCHAR2(100)
DEFAULT 'S/N' );




---INSERTAR REGISTROS 

SELECT * FROM producto2;

INSERT INTO PRODUCTO2 (PK_PRODUCTO, ID_UNO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, CADUCIDAD, EXISTENCIA,MARCA,STOCK_MINIMO) 
VALUES (5, 1, 'CAJAS', 'PAPELERIA', 100, TO_DATE('25/06/2003','DD/MM/YYYY'), 1, '', 30);


SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO=20;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO <>50;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO <100;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO >50;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO <=50;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO >=50;
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO BETWEEN 20 AND 50;
SELECT * FROM PRODUCTO2 WHERE NOMBRE LIKE 'C%'; ---- BUSCAR AL PRINCIPIO
SELECT * FROM PRODUCTO2 WHERE NOMBRE IN '%C%'; ------ BUSCAR EN MEDIO
SELECT * FROM PRODUCTO2 WHERE NOMBRE IN '%C'; ----- BUSCAR AL FINAL
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO IN (20,40,60);
SELECT * FROM PRODUCTO2 WHERE PRECIO_UNITARIO NOT IN (20,40,60);
SELECT * FROM PRODUCTO2 WHERE STOCK_MINIMO IS NULL;
SELECT * FROM PRODUCTO2 WHERE STOCK_MINIMO IS NOT NULL;












