CREATE TABLE alumnos (
PK_ALUMNO INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
APELLIDO_MATERNO VARCHAR2(50),
FECHA_NACIMIENTO DATE,
CURP CHAR(18),
RFC CHAR(13)
-- no poner coma en la ultima linea 
);

SELECT *FROM ALUMNOS;

INSERT INTO ALUMNOS ( PK_ALUMNO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, CURP, RFC)
VALUES (1, 'CARLOS', 'MORENO', 'PEDRO', TO_DATE('05/06/1997','DD/MM/YYYY'),'M0PC960505HV675437', '7394858596059');